version: '3.8'

services:
  fastapi:
    build: ./miAPI
    container_name: fastapi_backend
    ports:
      - "5000:5000"              
    volumes:
      - ./miAPI/app:/app/app      
    networks:
      - app_network

  flask:
    build: ./frontFlask
    container_name: flask_frontend
    ports:
      - "5001:5000"              
    environment:
      - FASTAPI_URL=http://fastapi:5000   # Nombre del servicio FastAPI dentro de Docker
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge