version: '3.8'

services:
  fastapi:
    build: ./miAPI
    container_name: fastapi_backend
    ports:
      - "5000:5000"               # Para acceder directamente desde tu navegador (opcional)
    volumes:
      - ./miAPI/app:/app/app      # Monta el código para recarga automática (solo desarrollo)
    networks:
      - app_network

  flask:
    build: ./frontFlask
    container_name: flask_frontend
    ports:
      - "5001:5000"               # Mapea el puerto 5000 del contenedor al 5001 del host (para no chocar con FastAPI)
    environment:
      - FASTAPI_URL=http://fastapi:5000   # Nombre del servicio FastAPI dentro de Docker
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge